ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "TwoFactorCode"          VARCHAR(6);
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "TwoFactorCodeExpiresAt" TIMESTAMPTZ;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "EmailVerified"          BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE "Users" DROP COLUMN IF EXISTS "TwoFactorEnabled";
